<a href="https://colab.research.google.com/github/TanviGupta7/First-repo-6-8-2024/blob/main/Copy_of_Tanvi_DA3rdsep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as numpy
df=pd.read_csv('/basics_data (1).csv')
df

F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
7    7   8   9   NaN  11.0  12      UK  green  Female
8    8   9  10   NaN  12.0  13     IND  green  Female
9    9  10  11  12.0  13.0  14      UK  green  Female
10  10  11  12  13.0   NaN  15     IND   blue  Female
11  11  12  13  14.0   NaN  16      UK   blue  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female

In [ ]:
#check missing values
#is null past version of isna
df.isna().sum()

F1         0
F2         0
F3         0
F4         2
F5         2
F6         0
Country    0
Color      0
Target     0
dtype: int64

In [ ]:
#Methods-1: Delete
df1=df.dropna()
df1

F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
9    9  10  11  12.0  13.0  14      UK  green  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female

In [ ]:
#Mathod2- Imputation
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=numpy.nan,strategy='mean')
imputer.fit(df.iloc[:,1:3])
df.iloc[:,1:3]=imputer.transform(df.iloc[:,1:3])#col F1 include till F3, F3 exclude
df
#

F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
7    7   8   9   NaN  11.0  12      UK  green  Female
8    8   9  10   NaN  12.0  13     IND  green  Female
9    9  10  11  12.0  13.0  14      UK  green  Female
10  10  11  12  13.0   NaN  15     IND   blue  Female
11  11  12  13  14.0   NaN  16      UK   blue  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female

In [ ]:
#Mathod2- Imputation
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=numpy.nan,strategy='most_frequent')
df.iloc[:,3:5]=si.fit_transform(df.iloc[:,3:5])
df

F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
7    7   8   9   3.0  11.0  12      UK  green  Female
8    8   9  10   3.0  12.0  13     IND  green  Female
9    9  10  11  12.0  13.0  14      UK  green  Female
10  10  11  12  13.0   4.0  15     IND   blue  Female
11  11  12  13  14.0   4.0  16      UK   blue  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female

In [ ]:
df.iloc[:,1:3]#index location i.e. identifying student by roll no.
df[['F2','F3']]#through col. name explicitly ie identifying student by name

F2  F3
0    1   2
1    2   3
2    3   4
3    4   5
4    5   6
5    6   7
6    7   8
7    8   9
8    9  10
9   10  11
10  11  12
11  12  13
12  13  14
13  14  15

In [ ]:
#Handle Categorical data
df['Target'].value_counts()


Target
Male      7
Female    7
Name: count, dtype: int64

In [ ]:
#Label Encoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Target']=le.fit_transform(df['Target'])
df

F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red       1
1    1   2   3   4.0   5.0   6      UK    red       1
2    2   3   4   5.0   6.0   7     IND    red       1
3    3   4   5   6.0   7.0   8      UK    red       1
4    4   5   6   7.0   8.0   9     IND  green       1
5    5   6   7   8.0   9.0  10      UK  green       1
6    6   7   8   9.0  10.0  11     IND  green       1
7    7   8   9   3.0  11.0  12      UK  green       0
8    8   9  10   3.0  12.0  13     IND  green       0
9    9  10  11  12.0  13.0  14      UK  green       0
10  10  11  12  13.0   4.0  15     IND   blue       0
11  11  12  13  14.0   4.0  16      UK   blue       0
12  12  13  14  15.0  16.0  17     IND   blue       0
13  13  14  15  16.0  17.0  18      UK   blue       0

In [ ]:
le.classes_

array(['Female', 'Male'], dtype=object)

In [ ]:
#Ordinal- hqas order,  NOMINAL- doesn't have order
#label encoder used for target while one hot encoder is used for country and color
#one hot encoder
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
df1=pd.DataFrame(ohe.fit_transform(df[['Color']]).toarray(),
columns=['Color_'+str(i) for i in range(len(df['Color'].value_counts()))])
df2=pd.concat([df,df1],axis=1)# initially color were 0,1,2 signifying 3 colors in table now we concat values
df3=df2.drop(['Color'],axis=1)
df3

F1  F2  F3    F4    F5  F6 Country  Target  Color_0  Color_1  Color_2
0    0   1   2   3.0   4.0   5     IND       1      0.0      0.0      1.0
1    1   2   3   4.0   5.0   6      UK       1      0.0      0.0      1.0
2    2   3   4   5.0   6.0   7     IND       1      0.0      0.0      1.0
3    3   4   5   6.0   7.0   8      UK       1      0.0      0.0      1.0
4    4   5   6   7.0   8.0   9     IND       1      0.0      1.0      0.0
5    5   6   7   8.0   9.0  10      UK       1      0.0      1.0      0.0
6    6   7   8   9.0  10.0  11     IND       1      0.0      1.0      0.0
7    7   8   9   3.0  11.0  12      UK       0      0.0      1.0      0.0
8    8   9  10   3.0  12.0  13     IND       0      0.0      1.0      0.0
9    9  10  11  12.0  13.0  14      UK       0      0.0      1.0      0.0
10  10  11  12  13.0   4.0  15     IND       0      1.0      0.0      0.0
11  11  12  13  14.0   4.0  16      UK       0      1.0      0.0      0.0
12  12  13  14  15.0  16.0  17     IND       0      1.0      0.0      0.0
13  13  14  15  16.0  17.0  18      UK       0      1.0      0.0      0.0

In [ ]:
#one hot encoder
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
df1=pd.DataFrame(ohe.fit_transform(df[['Country']]).toarray(),
columns=['Country_'+str(i) for i in range(len(df['Country'].value_counts()))])
df4=pd.concat([df3,df1],axis=1)# initially color were 0,1,2 signifying 3 colors in table now we concat values
df5=df4.drop(['Country'],axis=1)
df5
#label encoding- puts 0,1 value for india, uk but we do not know which one should be 0/1 neither it is target for which we can set the value for.
#we use one hot shot - it transforms country into 2 columns 1, 2 bec 2 countries ind, uk is given. it puts values as- when ind=1 uk =0 and vice versa for the netire value


F1  F2  F3    F4    F5  F6  Target  Color_0  Color_1  Color_2  Country_0  \
0    0   1   2   3.0   4.0   5       1      0.0      0.0      1.0        1.0   
1    1   2   3   4.0   5.0   6       1      0.0      0.0      1.0        0.0   
2    2   3   4   5.0   6.0   7       1      0.0      0.0      1.0        1.0   
3    3   4   5   6.0   7.0   8       1      0.0      0.0      1.0        0.0   
4    4   5   6   7.0   8.0   9       1      0.0      1.0      0.0        1.0   
5    5   6   7   8.0   9.0  10       1      0.0      1.0      0.0        0.0   
6    6   7   8   9.0  10.0  11       1      0.0      1.0      0.0        1.0   
7    7   8   9   3.0  11.0  12       0      0.0      1.0      0.0        0.0   
8    8   9  10   3.0  12.0  13       0      0.0      1.0      0.0        1.0   
9    9  10  11  12.0  13.0  14       0      0.0      1.0      0.0        0.0   
10  10  11  12  13.0   4.0  15       0      1.0      0.0      0.0        1.0   
11  11  12  13  14.0   4.0  16       0      1.0      0.0      0.0        0.0   
12  12  13  14  15.0  16.0  17       0      1.0      0.0      0.0        1.0   
13  13  14  15  16.0  17.0  18       0      1.0      0.0      0.0        0.0   

    Country_1  
0         0.0  
1         1.0  
2         0.0  
3         1.0  
4         0.0  
5         1.0  
6         0.0  
7         1.0  
8         0.0  
9         1.0  
10        0.0  
11        1.0  
12        0.0  
13        1.0

In [ ]:
y=df4['Target']
x=df5.drop(['Target'],axis=1)
print(x.shape)
print(y.shape)

(14, 11)
(14,)


In [ ]:
len(df['Color'].value_counts())

3

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=123)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
#Data frame- x(input), y(output)- xtest, train same for y
#11 features*

(9, 11)
(5, 11)
(9,)
(5,)


In [ ]:
print(x_test)

    F1  F2  F3    F4    F5  F6  Color_0  Color_1  Color_2  Country_0  \
7    7   8   9   3.0  11.0  12      0.0      1.0      0.0        0.0   
10  10  11  12  13.0   4.0  15      1.0      0.0      0.0        1.0   
4    4   5   6   7.0   8.0   9      0.0      1.0      0.0        1.0   
0    0   1   2   3.0   4.0   5      0.0      0.0      1.0        1.0   
5    5   6   7   8.0   9.0  10      0.0      1.0      0.0        0.0   

    Country_1  
7         1.0  
10        0.0  
4         0.0  
0         0.0  
5         1.0  


In [ ]:
#Feature Scaling method-1 - Standardization
# x0= (x-mean)/variance
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)
print(x_train_sc)
print(x_test_sc)


[[ 0.42222385  0.42222385  0.42222385  0.56011203  0.6634888   0.42222385
  -0.70710678  1.41421356 -0.70710678 -0.89442719  0.89442719]
 [ 0.18472293  0.18472293  0.18472293 -1.33026608  0.44232587  0.18472293
  -0.70710678  1.41421356 -0.70710678  1.11803399 -1.11803399]
 [ 0.89722568  0.89722568  0.89722568  0.98019606 -1.32697761  0.89722568
   1.41421356 -0.70710678 -0.70710678 -0.89442719  0.89442719]
 [-1.00278165 -1.00278165 -1.00278165 -0.70014004 -0.6634888  -1.00278165
  -0.70710678 -0.70710678  1.41421356 -0.89442719  0.89442719]
 [-1.47778348 -1.47778348 -1.47778348 -1.12022407 -1.10581467 -1.47778348
  -0.70710678 -0.70710678  1.41421356 -0.89442719  0.89442719]
 [-0.2902789  -0.2902789  -0.2902789  -0.070014    0.         -0.2902789
  -0.70710678  1.41421356 -0.70710678  1.11803399 -1.11803399]
 [ 1.1347266   1.1347266   1.1347266   1.19023807  1.32697761  1.1347266
   1.41421356 -0.70710678 -0.70710678  1.11803399 -1.11803399]
 [-1.24028256 -1.24028256 -1.24028256 -0.91

In [ ]:
#method-2 normalization
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
x_train_mms=mms.fit_transform(x_train)
x_test_mms=mms.transform(x_test)
print(x_train_mms)
print(x_test_mms)

[[0.66666667 0.66666667 0.66666667 0.69230769 0.69230769 0.66666667
  0.         1.         0.         0.         1.        ]
 [0.58333333 0.58333333 0.58333333 0.         0.61538462 0.58333333
  0.         1.         0.         1.         0.        ]
 [0.83333333 0.83333333 0.83333333 0.84615385 0.         0.83333333
  1.         0.         0.         0.         1.        ]
 [0.16666667 0.16666667 0.16666667 0.23076923 0.23076923 0.16666667
  0.         0.         1.         0.         1.        ]
 [0.         0.         0.         0.07692308 0.07692308 0.
  0.         0.         1.         0.         1.        ]
 [0.41666667 0.41666667 0.41666667 0.46153846 0.46153846 0.41666667
  0.         1.         0.         1.         0.        ]
 [0.91666667 0.91666667 0.91666667 0.92307692 0.92307692 0.91666667
  1.         0.         0.         1.         0.        ]
 [0.08333333 0.08333333 0.08333333 0.15384615 0.15384615 0.08333333
  0.         0.         1.         1.         0.        ]


In [ ]:
#Feature extraction
#Method-1, PCA
from sklearn.decomposition import PCA
#11 features out of which 2 have to be selected
pca=PCA(n_components=2)
x_train_pca=pca.fit_transform(x_train)#unsupervised learning where target(y) is not required
x_test_pca=pca.transform(x_test)
print(x_train_pca)
print(x_test_pca)
print(pca.explained_variance_ratio_)# print lambda
#find eigen value lambda , pca sort the lambda in descending order
#dimension reduction(reducing dimension of lambda) - 1)feature selection- as it is data goes 2) feature extraction(reduces dimension ie reduces perpendicular dimension of lambda )-i)pca, ii)lda
#llm-large lang. transformer

#tablet instead of food- same energy : this is the role of dimension reduction

[[ 1.10475347 -0.02067761]
 [-0.05006465  2.52904764]
 [ 2.05713875 -1.90102103]
 [-2.64386605 -1.51880861]
 [-3.64150303 -1.55268712]
 [-0.47278777  2.19298291]
 [ 3.14509767  0.89498621]
 [-3.22377031  0.72873042]
 [ 3.72500193 -1.35255282]]
[[-0.39593314  0.20985682]
 [ 1.53816414  0.39329889]
 [-1.47042476  2.15910439]
 [-4.22140729  0.69485191]
 [-0.8905205  -0.08843464]]
[0.60695839 0.22927908]


In [ ]:
#Method-2, Linear Discriminant Analysis LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=1)
x_train_lda=lda.fit_transform(x_train,y_train) #supervised learning- target y required ,min(n_features, n_classes-1).
x_test_lda=lda.transform(x_test)
print(x_train_lda)
print(x_test_lda)

[[-1.78770811]
 [-2.93694905]
 [-2.93694905]
 [ 2.23463514]
 [ 4.82042724]
 [ 2.52194538]
 [-2.07501835]
 [ 3.95849654]
 [-3.79887974]]
[[-1.71588056]
 [-1.05637298]
 [ 5.10773747]
 [ 6.54428863]
 [ 3.38387607]]
